### ISSUE TITLE
Integration doesn't show current state

### ISSUE THREAD

**Issue by slack1987** [And3rsL/VisonicAlarm-for-Hassio#15]
Since 15 days the integration doesn't update the current actual state of the alarm anymore, or it does just for a limited time after restarting HA.

If I manually restart HA, the integration refresh the correct state.

This is the error I found in the log:

```
Logger: homeassistant.helpers.entity
Source: custom_components/visonicalarm/__init__.py:119
First occurred: 28 gennaio 2021, 22:58:55 (25808 occurrences)
Last logged: 9:13:37

Update for sensor.visonic_alarm_204150 fails
Update for sensor.visonic_alarm_204152 fails
Update for sensor.visonic_alarm_204151 fails
Update for sensor.visonic_alarm_204149 fails
Update for sensor.visonic_alarm_204153 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 474, in async_device_update
    raise exc
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/visonicalarm/sensor.py", line 92, in update
    hub.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 259, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/visonicalarm/__init__.py", line 119, in update
    self.alarm.update_status()
  File "/usr/local/lib/python3.8/site-packages/visonic/alarm.py", line 350, in update_status
    partition = status['partitions'][0]
TypeError: 'NoneType' object is not subscriptable

```

**Comment by slack1987** [comment]
Dear @And3rsL I still have the same problem, did you find any solution?

Thank you so much in advance for your help and time.

**Comment by And3rsL** [comment]
i currently have no fix for this, it seems some problem with partitions.. do you have more than one?

**Comment by slack1987** [comment]
@And3rsL what do you mean with partitions? I have 2 users in the Visonic APP, and I just tried to remove one of them.

Can this be related with the issue?

I'll keep you update, thank you.

**Comment by And3rsL** [comment]
Please be sure that the user is the MASTER USER and you alredy added your panel in your registered account

**Comment by slack1987** [comment]
@And3rsL I used to have two users in the Visonic App and I thought this was causing the problem.
The integration worked fine for some hours then I start having the following errors:

**Error 1**
```
Logger: root
Source: /usr/local/lib/python3.8/site-packages/visonic/alarm.py:562
First occurred: 16 marzo 2021, 22:10:10 (9016 occurrences)
Last logged: 8:04:53

401 Client Error: Unauthorized for url: https://visonic.tycomonitor.com/rest_api/8.0/status
```
**Error 2**
```
Logger: root
Source: /usr/local/lib/python3.8/site-packages/visonic/alarm.py:563
First occurred: 16 marzo 2021, 22:10:10 (9016 occurrences)
Last logged: 8:04:53

{"error":10003,"error_message":"Wrong user token","error_reason_code":"WrongUserToken","extras":null}
```
**Error 3**
```
Logger: root
Source: /usr/local/lib/python3.8/site-packages/visonic/alarm.py:572
First occurred: 16 marzo 2021, 22:10:10 (9016 occurrences)
Last logged: 8:04:53

{"error":10003,"error_message":"Wrong user token","error_reason_code":"WrongUserToken","extras":null}
```
**Error 4**
```
Logger: custom_components.visonicalarm
Source: custom_components/visonicalarm/__init__.py:127
Integration: Visonic/Bentel/Tyco Alarm System (documentation)
First occurred: 16 marzo 2021, 22:10:09 (9018 occurrences)
Last logged: 8:04:53

Update failed: HTTPSConnectionPool(host='visonic.tycomonitor.com', port=443): Read timed out. (read timeout=None)
Update failed: 'NoneType' object is not subscriptable
Update failed: ('Connection aborted.', OSError(101, 'Network unreachable'))
```
**Error 5**
```
Logger: homeassistant.helpers.entity
Source: custom_components/visonicalarm/__init__.py:119
First occurred: 16 marzo 2021, 22:10:10 (9016 occurrences)
Last logged: 8:04:53

Update for sensor.visonic_alarm_204149 fails
Update for sensor.visonic_alarm_204151 fails
Update for sensor.visonic_alarm_204152 fails
Update for sensor.visonic_alarm_204153 fails
Update for alarm_control_panel.visonic_alarm fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 277, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 473, in async_device_update
    raise exc
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/visonicalarm/alarm_control_panel.py", line 153, in update
    hub.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 285, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/visonicalarm/__init__.py", line 119, in update
    self.alarm.update_status()
  File "/usr/local/lib/python3.8/site-packages/visonic/alarm.py", line 350, in update_status
    partition = status['partitions'][0]
TypeError: 'NoneType' object is not subscriptable
```

Attached you can find the screenshot of the users page from the Visonic APP.

Any idea?

Thank you again for your help, ciao!
![Picture1](https://user-images.githubusercontent.com/64207585/111472097-edebe200-8729-11eb-8a5d-daa743613fff.jpg)

**Comment by And3rsL** [comment]
it seems that login fail.. can you double check your username and password? do you have any strange character in your password?

**Comment by slack1987** [comment]
@And3rsL, 
I used to have a [ character in the password.
I tried change username and password, but the behavior remain the same, the integration works for some hours, and then I start having the errors again.

Any idea? the only thing I can think about it is:
Is there a way to restart the integration automatically every 10 minutes or so? I know is not a solution but it's something.

Thank you, ciao.

**Comment by And3rsL** [comment]
Ok got it, i will try fix it soon

**Comment by slack1987** [comment]
@And3rsL  I also receive the following alarm if it can help:

```
Logger: homeassistant.components.alarm_control_panel
Source: helpers/entity_platform.py:605
Integration: Pannello di Controllo degli Allarmi (documentation, issues)
First occurred: 12:30:20 (99 occurrences)
Last logged: 12:46:40

Updating visonicalarm alarm_control_panel took longer than the scheduled update interval 0:00:10
```
Ciao.
