### ISSUE TITLE
Component stop working after a few days

### ISSUE THREAD

**Issue by a94marbo** [And3rsL/VisonicAlarm-for-Hassio#4]
Reboot make the component work again.
Last error message before the component stops updating is:
"Update of alarm_control_panel.visonic_alarm is taking over 10 seconds
29 januari 2020 10:45 __main__.py (WARNING)"

Not much to go on...

I am running 0.104.3

**Comment by And3rsL** [comment]
The component requires that alarm is connected to its cloud, if your home assistant lose connection it requires wake up alarm by sending sms in the official app

**Comment by a94marbo** [comment]
Ok, I tried this again now when it became unresponsive again during the night. I logged in via the app, and the connection is working. However home assistant do not reconnect.
It starts with a number of servies that drops their connection, like Ring, VolvoOnCall and Visonic. But most of them reconnect, but not Visonic. 
I then get these messages in the log:
`Update failed: 440 Client Error: Session token not found for url: https://first-support.alarmsystem.dk/rest_api/4.0/status`
and this

```
Update for alarm_control_panel.visonic_alarm fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 461, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/visonicalarm/alarm_control_panel.py", line 146, in update
    hub.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 240, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/visonicalarm/__init__.py", line 113, in update
    self.alarm.update_status()
  File "/usr/local/lib/python3.7/site-packages/visonic/alarm.py", line 416, in update_status
    status = self.__api.get_status()
  File "/usr/local/lib/python3.7/site-packages/visonic/alarm.py", line 737, in get_status
    with_session_token=True)
  File "/usr/local/lib/python3.7/site-packages/visonic/alarm.py", line 630, in __send_get_request
    response.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 440 Client Error: Session token not found for url: https://first-support.alarmsystem.dk/rest_api/4.0/status
```

**Comment by And3rsL** [comment]
Ok, next push i will try to fix it
maybe it lose connection and new token is needed

**Comment by a94marbo** [comment]
The problem have stopped, maybe a problem with my Powermanager server.
